## Evaluate the performance of the best ML-Pipeline trained on the annotations of rater 1 on the annotaions of rater 2

### Setup and Helper Functions

#### Imports

In [12]:
import pandas as pd
import numpy as np
from pathlib import Path

#### Datapaths

In [3]:
data_path = Path("../../results")

### Load data

In [4]:
rater_02 = pd.read_csv(data_path.joinpath("combined_data_rater_02.csv"), index_col=[0,1,2,3,4])
rater_02.index = rater_02.index.droplevel(0)
ml_results = pd.read_csv(data_path.joinpath("merged_ml_results_b_point_paper_rr_only.csv"), index_col=[0,1,2,3])
intersecting_ids = ml_results.index.intersection(rater_02.index)

#### Select intersecting cardiac cycles between rater 1 and rater 2
- The mismatch comes from the fact that some cardiac cycles may have been excluded by rater 1, while rater 2 included them or vice versa (Exclusion criteria may involve severe artefacts)

In [ ]:
ml_results.loc[intersecting_ids]

                                                            b_point_sample_reference  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          388.0
                                    1                                          404.0
                                    3                                          376.0
                                    4                                          390.0
                                    5                                          386.0
...                                                                              ...
VP_032      tsst      Talk          39                                         310.0
                                    40                                         322.0
                                    41                                         340.0
                                    42                                         311.0
                                    43                                         307.0

                                                            arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 438.0
                                    1                                                 340.0
                                    3                                                 382.0
                                    4                                                 394.0
                                    5                                                 398.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                335.0
                                    40                                                331.0
                                    41                                                317.0
                                    42                                                365.0
                                    43                                                342.0

                                                            arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                             398.0
                                    1                                             350.0
                                    3                                             296.0
                                    4                                             344.0
                                    5                                             312.0
...                                                                                 ...
VP_032      tsst      Talk          39                                            276.0
                                    40                                            298.0
                                    41                                            300.0
                                    42                                            324.0
                                    43                                            313.0

                                                            arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                            394.0
                                    1                                            244.0
                                    3                                            386.0
                                    4                                            396.0
                                    5                                            388.0
...                                                                                ...
VP_032      tsst      Talk          39                                           324.0
                                    40                                           330.0
                                    41                                           348.0
                                    42                                           366.0
                                    43                                           356.0

                                                            debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              452.0
                                    1                                              388.0
                                    3                                              366.0
                                    4                                              376.0
                                    5                                              418.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             300.0
                                    40                                             311.0
                                    41                                             330.0
                                    42                                             347.0
                                    43                                             285.0

                                                            drost2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           400.0
                                    1                           420.0
                                    3                           386.0
                                    4                           396.0
                                    5                           392.0
...                                                               ...
VP_032      tsst      Talk          39                          318.0
                                    40                          322.0
                                    41                          343.0
                                    42                          354.0
                                    43                          332.0

                                                            forouzanfar2018  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 550.0
                                    1                                 402.0
                                    3                                 388.0
                                    4                                 398.0
                                    5                                 390.0
...                                                                     ...
VP_032      tsst      Talk          39                                306.0
                                    40                                311.0
                                    41                                309.0
                                    42                                305.0
                                    43                                302.0

                                                            lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              412.0
                                    1                                              404.0
                                    3                                              366.0
                                    4                                              372.0
                                    5                                              378.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             305.0
                                    40                                             321.0
                                    41                                             332.0
                                    42                                             351.0
                                    43                                             341.0

                                                            lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 384.0
                                    1                                                 384.0
                                    3                                                 348.0
                                    4                                                 348.0
                                    5                                                 354.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                294.0
                                    40                                                303.0
                                    41                                                322.0
                                    42                                                337.0
                                    43                                                329.0

                                                            miljkovic2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                               442.0
                                    1                               288.0
                                    3                               386.0
                                    4                               398.0
                                    5                               392.0
...                                                                   ...
VP_032      tsst      Talk          39                              308.0
                                    40                              329.0
                                    41                              292.0
                                    42                              312.0
                                    43                              334.0

                                                            ...  \
participant condition phase         heartbeat_id_reference  ...
GDN0005     Dummy     HoldingBreath 0                       ...
                                    1                       ...
                                    3                       ...
                                    4                       ...
                                    5                       ...
...                                                         ...
VP_032      tsst      Talk          39                      ...
                                    40                      ...
                                    41                      ...
                                    42                      ...
                                    43                      ...

                                                            SS_KBest_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    412.398584
                                    1                                                    403.408903
                                    3                                                    376.768489
                                    4                                                    388.625256
                                    5                                                    385.761830
...                                                                                             ...
VP_032      tsst      Talk          39                                                   309.424969
                                    40                                                   312.280534
                                    41                                                   331.079043
                                    42                                                   342.187956
                                    43                                                   307.324979

                                                            SS_KBest_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    421.288455
                                    1                                                    401.485786
                                    3                                                    376.403625
                                    4                                                    388.643213
                                    5                                                    386.743597
...                                                                                             ...
VP_032      tsst      Talk          39                                                   319.918637
                                    40                                                   317.460122
                                    41                                                   329.227094
                                    42                                                   339.654610
                                    43                                                   314.443751

                                                            MinMax_SFM_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                           392.0
                                    1                                                           406.0
                                    3                                                           376.0
                                    4                                                           388.0
                                    5                                                           384.0
...                                                                                               ...
VP_032      tsst      Talk          39                                                          311.0
                                    40                                                          321.0
                                    41                                                          334.0
                                    42                                                          351.5
                                    43                                                          307.5

                                                            MinMax_SFM_RFR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      430.592322
                                    1                                                      404.075637
                                    3                                                      375.332204
                                    4                                                      389.011683
                                    5                                                      385.868359
...                                                                                               ...
VP_032      tsst      Talk          39                                                     310.134872
                                    40                                                     317.331053
                                    41                                                     330.211990
                                    42                                                     335.669733
                                    43                                                     310.617416

                                                            MinMax_SFM_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      415.841272
                                    1                                                      405.752970
                                    3                                                      377.956802
                                    4                                                      388.530034
                                    5                                                      386.934831
...                                                                                               ...
VP_032      tsst      Talk          39                                                     308.018902
                                    40                                                     310.554869
                                    41                                                     330.103150
                                    42                                                     339.014104
                                    43                                                     313.036780

                                                            MinMax_SFM_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                      416.688480
                                    1                                                      396.160236
                                    3                                                      377.268411
                                    4                                                      387.233813
                                    5                                                      390.040129
...                                                                                               ...
VP_032      tsst      Talk          39                                                     310.277235
                                    40                                                     315.145165
                                    41                                                     329.741920
                                    42                                                     342.487887
                                    43                                                     306.995532

                                                            MinMax_KBest_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                             403.0
                                    1                                                             404.0
                                    3                                                             376.0
                                    4                                                             388.0
                                    5                                                             386.0

In [6]:
rater_02.loc[intersecting_ids]

                                                            b_point_sample_reference  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          388.0
                                    1                                          406.0
                                    3                                          374.0
                                    4                                          390.0
                                    5                                          384.0
...                                                                              ...
VP_032      tsst      Talk          39                                         312.0
                                    40                                         314.0
                                    41                                         333.0
                                    42                                         312.0
                                    43                                         300.0

                                                            rr_interval_ms_estimated  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          850.0
                                    1                                          778.0
                                    3                                          746.0
                                    4                                          766.0
                                    5                                          790.0
...                                                                              ...
VP_032      tsst      Talk          39                                         619.0
                                    40                                         680.0
                                    41                                         719.0
                                    42                                         698.0
                                    43                                         689.0

                                                            arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 438.0
                                    1                                                 340.0
                                    3                                                 382.0
                                    4                                                 394.0
                                    5                                                 398.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                335.0
                                    40                                                331.0
                                    41                                                317.0
                                    42                                                365.0
                                    43                                                342.0

                                                            arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                             398.0
                                    1                                             350.0
                                    3                                             296.0
                                    4                                             344.0
                                    5                                             312.0
...                                                                                 ...
VP_032      tsst      Talk          39                                            276.0
                                    40                                            298.0
                                    41                                            300.0
                                    42                                            324.0
                                    43                                            313.0

                                                            arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                            394.0
                                    1                                            244.0
                                    3                                            386.0
                                    4                                            396.0
                                    5                                            388.0
...                                                                                ...
VP_032      tsst      Talk          39                                           324.0
                                    40                                           330.0
                                    41                                           348.0
                                    42                                           366.0
                                    43                                           356.0

                                                            debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              452.0
                                    1                                              388.0
                                    3                                              366.0
                                    4                                              376.0
                                    5                                              418.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             300.0
                                    40                                             311.0
                                    41                                             330.0
                                    42                                             347.0
                                    43                                             285.0

                                                            drost2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           400.0
                                    1                           420.0
                                    3                           386.0
                                    4                           396.0
                                    5                           392.0
...                                                               ...
VP_032      tsst      Talk          39                          318.0
                                    40                          322.0
                                    41                          343.0
                                    42                          354.0
                                    43                          332.0

                                                            forouzanfar2018  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 550.0
                                    1                                 402.0
                                    3                                 388.0
                                    4                                 398.0
                                    5                                 390.0
...                                                                     ...
VP_032      tsst      Talk          39                                306.0
                                    40                                311.0
                                    41                                309.0
                                    42                                305.0
                                    43                                302.0

                                                            lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              412.0
                                    1                                              404.0
                                    3                                              366.0
                                    4                                              372.0
                                    5                                              378.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             305.0
                                    40                                             321.0
                                    41                                             332.0
                                    42                                             351.0
                                    43                                             341.0

                                                            lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 384.0
                                    1                                                 384.0
                                    3                                                 348.0
                                    4                                                 348.0
                                    5                                                 354.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                294.0
                                    40                                                303.0
                                    41                                                322.0
                                    42                                                337.0
                                    43                                                329.0

                                                            miljkovic2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                               442.0
                                    1                               288.0
                                    3                               386.0
                                    4                               398.0
                                    5                               392.0
...                                                                   ...
VP_032      tsst      Talk          39                              308.0
                                    40                              329.0
                                    41                              292.0
                                    42                              312.0
                                    43                              334.0

                                                            pale2021  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                          388.0
                                    1                          246.0
                                    3                          374.0
                                    4                          388.0
                                    5                          384.0
...                                                              ...
VP_032      tsst      Talk          39                         306.0
                                    40                          85.0
                                    41                          14.0
                                    42                         261.0
                                    43                         302.0

                                                            sherwood1990  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                              442.0
                                    1                              330.0
                                    3                              382.0
                                    4                              394.0
                                    5                              400.0
...                                                                  ...
VP_032      tsst      Talk          39                             337.0
                                    40                             329.0
                                    41                             311.0
                                    42                             368.0
                                    43                             334.0

                                                            stern1985
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           388.0
                                    1                           402.0
                                    3                           374.0
                                    4                           388.0
                                    5                           384.0
...                                                               ...
VP_032      tsst      Talk          39                          306.0
                                    40                          287.0
                                    41                          287.0
                                    42                          305.0
                                    43                          301.0

[10911 rows x 14 columns]

### Join best ML-Pipeline predictions to the dataframe with annotations of rater 2

In [8]:
performance_rater_2 = rater_02.loc[intersecting_ids].join(ml_results.loc[intersecting_ids, ['MinMax_None_RFR_RR-Interval-Include-Nan']])
performance_rater_2

                                                            b_point_sample_reference  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          388.0
                                    1                                          406.0
                                    3                                          374.0
                                    4                                          390.0
                                    5                                          384.0
...                                                                              ...
VP_032      tsst      Talk          39                                         312.0
                                    40                                         314.0
                                    41                                         333.0
                                    42                                         312.0
                                    43                                         300.0

                                                            rr_interval_ms_estimated  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          850.0
                                    1                                          778.0
                                    3                                          746.0
                                    4                                          766.0
                                    5                                          790.0
...                                                                              ...
VP_032      tsst      Talk          39                                         619.0
                                    40                                         680.0
                                    41                                         719.0
                                    42                                         698.0
                                    43                                         689.0

                                                            arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 438.0
                                    1                                                 340.0
                                    3                                                 382.0
                                    4                                                 394.0
                                    5                                                 398.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                335.0
                                    40                                                331.0
                                    41                                                317.0
                                    42                                                365.0
                                    43                                                342.0

                                                            arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                             398.0
                                    1                                             350.0
                                    3                                             296.0
                                    4                                             344.0
                                    5                                             312.0
...                                                                                 ...
VP_032      tsst      Talk          39                                            276.0
                                    40                                            298.0
                                    41                                            300.0
                                    42                                            324.0
                                    43                                            313.0

                                                            arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                            394.0
                                    1                                            244.0
                                    3                                            386.0
                                    4                                            396.0
                                    5                                            388.0
...                                                                                ...
VP_032      tsst      Talk          39                                           324.0
                                    40                                           330.0
                                    41                                           348.0
                                    42                                           366.0
                                    43                                           356.0

                                                            debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              452.0
                                    1                                              388.0
                                    3                                              366.0
                                    4                                              376.0
                                    5                                              418.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             300.0
                                    40                                             311.0
                                    41                                             330.0
                                    42                                             347.0
                                    43                                             285.0

                                                            drost2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           400.0
                                    1                           420.0
                                    3                           386.0
                                    4                           396.0
                                    5                           392.0
...                                                               ...
VP_032      tsst      Talk          39                          318.0
                                    40                          322.0
                                    41                          343.0
                                    42                          354.0
                                    43                          332.0

                                                            forouzanfar2018  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 550.0
                                    1                                 402.0
                                    3                                 388.0
                                    4                                 398.0
                                    5                                 390.0
...                                                                     ...
VP_032      tsst      Talk          39                                306.0
                                    40                                311.0
                                    41                                309.0
                                    42                                305.0
                                    43                                302.0

                                                            lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              412.0
                                    1                                              404.0
                                    3                                              366.0
                                    4                                              372.0
                                    5                                              378.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             305.0
                                    40                                             321.0
                                    41                                             332.0
                                    42                                             351.0
                                    43                                             341.0

                                                            lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 384.0
                                    1                                                 384.0
                                    3                                                 348.0
                                    4                                                 348.0
                                    5                                                 354.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                294.0
                                    40                                                303.0
                                    41                                                322.0
                                    42                                                337.0
                                    43                                                329.0

                                                            miljkovic2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                               442.0
                                    1                               288.0
                                    3                               386.0
                                    4                               398.0
                                    5                               392.0
...                                                                   ...
VP_032      tsst      Talk          39                              308.0
                                    40                              329.0
                                    41                              292.0
                                    42                              312.0
                                    43                              334.0

                                                            pale2021  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                          388.0
                                    1                          246.0
                                    3                          374.0
                                    4                          388.0
                                    5                          384.0
...                                                              ...
VP_032      tsst      Talk          39                         306.0
                                    40                          85.0
                                    41                          14.0
                                    42                         261.0
                                    43                         302.0

                                                            sherwood1990  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                              442.0
                                    1                              330.0
                                    3                              382.0
                                    4                              394.0
                                    5                              400.0
...                                                                  ...
VP_032      tsst      Talk          39                             337.0
                                    40                             329.0
                                    41                             311.0
                                    42                             368.0
                                    43                             334.0

                                                            stern1985  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           388.0
                                    1                           402.0
                                    3                           374.0
                                    4                           388.0
                                    5                           384.0
...                                                               ...
VP_032      tsst      Talk          39                          306.0
                                    40                          287.0
                                    41                          287.0
                                    42                          305.0
                                    43                          301.0

                                                            MinMax_None_RFR_RR-Interval-Include-Nan
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    419.768000
                                    1                                                    403.352000
                                    3                                                    375.744000
                                    4                                                    388.706400
                                    5                                                    386.088444
...                                                                                             ...
VP_032      tsst      Talk          39                                                   310.040000
                                    40                                                   316.340000
                                    41                                                   324.832000
                                    42                                                   337.744000
                                    43                                                   307.900000

[10911 rows x 15 columns]

### Compute the error of the best ML-Pipeline on the annotations of rater 2

In [13]:
performance_rater_2['ml_prediction_error'] = performance_rater_2['MinMax_None_RFR_RR-Interval-Include-Nan'] - performance_rater_2['b_point_sample_reference']
performance_rater_2['ml_prediction_abs_error'] = np.abs(performance_rater_2['MinMax_None_RFR_RR-Interval-Include-Nan'] - performance_rater_2['b_point_sample_reference'])
performance_rater_2

                                                            b_point_sample_reference  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          388.0
                                    1                                          406.0
                                    3                                          374.0
                                    4                                          390.0
                                    5                                          384.0
...                                                                              ...
VP_032      tsst      Talk          39                                         312.0
                                    40                                         314.0
                                    41                                         333.0
                                    42                                         312.0
                                    43                                         300.0

                                                            rr_interval_ms_estimated  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                          850.0
                                    1                                          778.0
                                    3                                          746.0
                                    4                                          766.0
                                    5                                          790.0
...                                                                              ...
VP_032      tsst      Talk          39                                         619.0
                                    40                                         680.0
                                    41                                         719.0
                                    42                                         698.0
                                    43                                         689.0

                                                            arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 438.0
                                    1                                                 340.0
                                    3                                                 382.0
                                    4                                                 394.0
                                    5                                                 398.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                335.0
                                    40                                                331.0
                                    41                                                317.0
                                    42                                                365.0
                                    43                                                342.0

                                                            arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                             398.0
                                    1                                             350.0
                                    3                                             296.0
                                    4                                             344.0
                                    5                                             312.0
...                                                                                 ...
VP_032      tsst      Talk          39                                            276.0
                                    40                                            298.0
                                    41                                            300.0
                                    42                                            324.0
                                    43                                            313.0

                                                            arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                            394.0
                                    1                                            244.0
                                    3                                            386.0
                                    4                                            396.0
                                    5                                            388.0
...                                                                                ...
VP_032      tsst      Talk          39                                           324.0
                                    40                                           330.0
                                    41                                           348.0
                                    42                                           366.0
                                    43                                           356.0

                                                            debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              452.0
                                    1                                              388.0
                                    3                                              366.0
                                    4                                              376.0
                                    5                                              418.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             300.0
                                    40                                             311.0
                                    41                                             330.0
                                    42                                             347.0
                                    43                                             285.0

                                                            drost2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           400.0
                                    1                           420.0
                                    3                           386.0
                                    4                           396.0
                                    5                           392.0
...                                                               ...
VP_032      tsst      Talk          39                          318.0
                                    40                          322.0
                                    41                          343.0
                                    42                          354.0
                                    43                          332.0

                                                            forouzanfar2018  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 550.0
                                    1                                 402.0
                                    3                                 388.0
                                    4                                 398.0
                                    5                                 390.0
...                                                                     ...
VP_032      tsst      Talk          39                                306.0
                                    40                                311.0
                                    41                                309.0
                                    42                                305.0
                                    43                                302.0

                                                            lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                              412.0
                                    1                                              404.0
                                    3                                              366.0
                                    4                                              372.0
                                    5                                              378.0
...                                                                                  ...
VP_032      tsst      Talk          39                                             305.0
                                    40                                             321.0
                                    41                                             332.0
                                    42                                             351.0
                                    43                                             341.0

                                                            lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                 384.0
                                    1                                                 384.0
                                    3                                                 348.0
                                    4                                                 348.0
                                    5                                                 354.0
...                                                                                     ...
VP_032      tsst      Talk          39                                                294.0
                                    40                                                303.0
                                    41                                                322.0
                                    42                                                337.0
                                    43                                                329.0

                                                            miljkovic2022  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                               442.0
                                    1                               288.0
                                    3                               386.0
                                    4                               398.0
                                    5                               392.0
...                                                                   ...
VP_032      tsst      Talk          39                              308.0
                                    40                              329.0
                                    41                              292.0
                                    42                              312.0
                                    43                              334.0

                                                            pale2021  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                          388.0
                                    1                          246.0
                                    3                          374.0
                                    4                          388.0
                                    5                          384.0
...                                                              ...
VP_032      tsst      Talk          39                         306.0
                                    40                          85.0
                                    41                          14.0
                                    42                         261.0
                                    43                         302.0

                                                            sherwood1990  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                              442.0
                                    1                              330.0
                                    3                              382.0
                                    4                              394.0
                                    5                              400.0
...                                                                  ...
VP_032      tsst      Talk          39                             337.0
                                    40                             329.0
                                    41                             311.0
                                    42                             368.0
                                    43                             334.0

                                                            stern1985  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                           388.0
                                    1                           402.0
                                    3                           374.0
                                    4                           388.0
                                    5                           384.0
...                                                               ...
VP_032      tsst      Talk          39                          306.0
                                    40                          287.0
                                    41                          287.0
                                    42                          305.0
                                    43                          301.0

                                                            MinMax_None_RFR_RR-Interval-Include-Nan  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                                    419.768000
                                    1                                                    403.352000
                                    3                                                    375.744000
                                    4                                                    388.706400
                                    5                                                    386.088444
...                                                                                             ...
VP_032      tsst      Talk          39                                                   310.040000
                                    40                                                   316.340000
                                    41                                                   324.832000
                                    42                                                   337.744000
                                    43                                                   307.900000

                                                            ml_prediction_error  \
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                 31.768000
                                    1                                 -2.648000
                                    3                                  1.744000
                                    4                                 -1.293600
                                    5                                  2.088444
...                                                                         ...
VP_032      tsst      Talk          39                                -1.960000
                                    40                                 2.340000
                                    41                                -8.168000
                                    42                                25.744000
                                    43                                 7.900000

                                                            ml_prediction_abs_error
participant condition phase         heartbeat_id_reference
GDN0005     Dummy     HoldingBreath 0                                     31.768000
                                    1                                      2.648000
                                    3                                      1.744000
                                    4                                      1.293600
                                    5                                      2.088444
...                                                                             ...
VP_032      tsst      Talk          39                                     1.960000
                                    40                                     2.340000
                                    41                                     8.168000
                                    42                                    25.744000
                                    43                                     7.900000

[10911 rows x 17 columns]

In [14]:
performance_rater_2.describe()

,b_point_sample_reference,rr_interval_ms_estimated,arbol2017-isoelectric-crossings,arbol2017-second-derivative,arbol2017-third-derivative,debski1993-second-derivative,drost2022,forouzanfar2018,lozano2007-linear-regression,lozano2007-quadratic-regression,miljkovic2022,pale2021,sherwood1990,stern1985,MinMax_None_RFR_RR-Interval-Include-Nan,ml_prediction_error,ml_prediction_abs_error
count,10911.000000,10813.000000,10904.000000,10911.000000,10909.000000,10520.000000,10911.000000,10768.000000,10911.000000,10911.000000,10911.000000,10911.000000,10662.000000,10890.000000,10911.000000,10911.000000,10911.000000
mean,361.418568,802.601221,366.460932,325.475209,355.346228,373.206654,377.518651,346.954681,376.446064,360.547429,359.018788,292.276968,369.589852,337.142424,365.656465,4.237897,10.021989
std,100.591040,224.278204,98.924904,106.525311,113.796221,106.628724,104.186424,111.411457,93.185417,86.786792,102.902832,147.933784,95.910477,113.337869,98.809299,17.140985,14.537032
min,123.000000,380.000000,4.000000,-87.000000,-231.000000,137.000000,-31.000000,-254.000000,85.000000,-180.000000,-254.000000,-23.000000,142.000000,0.000000,157.468000,-247.236000,0.000764
25%,276.000000,636.000000,291.000000,245.000000,274.000000,293.000000,293.000000,248.000000,306.000000,300.500000,285.000000,218.000000,296.000000,238.000000,285.310270,-2.948317,1.695474
50%,370.000000,799.000000,374.000000,332.000000,363.000000,379.000000,389.000000,356.000000,380.000000,362.000000,364.000000,295.000000,375.000000,348.000000,372.788000,0.746802,4.370845
75%,440.000000,952.000000,436.000000,402.000000,434.000000,456.000000,456.000000,434.000000,444.000000,420.000000,432.000000,403.000000,438.000000,428.000000,441.887106,6.848099,11.788263
max,650.000000,1534.000000,654.000000,642.000000,660.000000,708.000000,646.000000,742.000000,654.000000,622.000000,650.000000,664.000000,650.000000,686.000000,612.303346,126.227420,247.236000