## Merge the ML-Pipeline results of multiple Experiments (including Experiment 1 & 2) with the traditional B-Point detection algorithms

### Setup and Helper Functions

#### Imports

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from b_point_ml_experiments.data_handling import build_ml_results_df
from b_point_ml_experiments.data_handling import merge_ml_result_dfs

#### Datapaths

In [3]:
model_path = Path("../../models")
data_path = Path("../../results")
rater = "rater_01"

### Combine ML-Pipeline results with traditional B-Point detection algorithm data

#### Master dataframe where to merge the ML-Pipeline results into

In [4]:
# The dataframe with the most cardiac cycles was chosen as the master dataframe
b_point_master = pd.read_csv(data_path.joinpath(f"without-rr-interval/{rater}/train_data_b_point_include_nan_ml_results.csv"), index_col=[0,1,2,3,4,5])
b_point_master

,,,,,,arbol2017-isoelectric-crossings,arbol2017-second-derivative,arbol2017-third-derivative,debski1993-second-derivative,drost2022,forouzanfar2018,lozano2007-linear-regression,lozano2007-quadratic-regression,miljkovic2022,pale2021,sherwood1990,stern1985,SS_None_DTR_Without-RR-Interval-Include-Nan,SS_None_RFR_Without-RR-Interval-Include-Nan,MinMax_None_DTR_Without-RR-Interval-Include-Nan,MinMax_None_RFR_Without-RR-Interval-Include-Nan
,participant,condition,phase,heartbeat_id_reference,b_point_sample_reference,,,,,,,,,,,,,,,,
0,GDN0005,Dummy,HoldingBreath,0,388.0,438.0,398.0,394.0,452.0,400.0,550.0,412.0,384.0,442.0,388.0,442.0,388.0,385.134146,420.853602,385.134146,419.560000
1,GDN0005,Dummy,HoldingBreath,1,404.0,340.0,350.0,244.0,388.0,420.0,402.0,404.0,384.0,288.0,246.0,330.0,402.0,402.913580,403.107493,402.913580,403.696000
2,GDN0005,Dummy,HoldingBreath,3,376.0,382.0,296.0,386.0,366.0,386.0,388.0,366.0,348.0,386.0,374.0,382.0,374.0,385.134146,375.676340,385.134146,375.456000
3,GDN0005,Dummy,HoldingBreath,4,390.0,394.0,344.0,396.0,376.0,396.0,398.0,372.0,348.0,398.0,388.0,394.0,388.0,385.134146,388.942668,385.134146,388.575765
4,GDN0005,Dummy,HoldingBreath,5,386.0,398.0,312.0,388.0,418.0,392.0,390.0,378.0,354.0,392.0,384.0,400.0,384.0,385.134146,385.815711,385.134146,385.931500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11234,VP_032,tsst,Talk,39,310.0,335.0,276.0,324.0,300.0,318.0,306.0,305.0,294.0,308.0,306.0,337.0,306.0,305.344444,310.776605,305.344444,310.468500
11235,VP_032,tsst,Talk,40,322.0,331.0,298.0,330.0,311.0,322.0,311.0,321.0,303.0,329.0,85.0,329.0,287.0,316.931818,317.288515,316.931818,316.784000
11236,VP_032,tsst,Talk,41,340.0,317.0,300.0,348.0,330.0,343.0,309.0,332.0,322.0,292.0,14.0,311.0,287.0,324.513158,320.424675,324.513158,324.660000
11237,VP_032,tsst,Talk,42,311.0,365.0,324.0,366.0,347.0,354.0,305.0,351.0,337.0,312.0,261.0,368.0,305.0,335.626168,340.305390,335.626168,334.772000
11238,VP_032,tsst,Talk,43,307.0,342.0,313.0,356.0,285.0,332.0,302.0,341.0,329.0,334.0,302.0,334.0,301.0,304.933333,307.356460,304.933333,307.272000

#### Merge ML-Pipeline results in master dataframe

In [5]:
merged_ml_results_b_point = merge_ml_result_dfs(data_path, master_df=b_point_master, event='b_point')
merged_ml_results_b_point

..\..\..\results\data\b-point\rr-interval\rater_01\train_data_b_point_rr_interval_include_nan_ml_results.csv
Detected duplicate column:  level_0
..\..\..\results\data\b-point\rr-interval\rater_01\train_data_b_point_rr_interval_median_imputed_ml_results.csv
Detected duplicate column:  level_0
Detected duplicate column:  rr_interval_ms_estimated

                                                                                     level_0  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                           0
                                    1                      404.0                           1
                                    3                      376.0                           2
                                    4                      390.0                           3
                                    5                      386.0                           4
...                                                                                      ...
VP_032      tsst      Talk          39                     310.0                       11234
                                    40                     322.0                       11235
                                    41                     340.0                       11236
                                    42                     311.0                       11237
                                    43                     307.0                       11238

                                                                                     arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                               438.0
                                    1                      404.0                                               340.0
                                    3                      376.0                                               382.0
                                    4                      390.0                                               394.0
                                    5                      386.0                                               398.0
...                                                                                                              ...
VP_032      tsst      Talk          39                     310.0                                               335.0
                                    40                     322.0                                               331.0
                                    41                     340.0                                               317.0
                                    42                     311.0                                               365.0
                                    43                     307.0                                               342.0

                                                                                     arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                           398.0
                                    1                      404.0                                           350.0
                                    3                      376.0                                           296.0
                                    4                      390.0                                           344.0
                                    5                      386.0                                           312.0
...                                                                                                          ...
VP_032      tsst      Talk          39                     310.0                                           276.0
                                    40                     322.0                                           298.0
                                    41                     340.0                                           300.0
                                    42                     311.0                                           324.0
                                    43                     307.0                                           313.0

                                                                                     arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                          394.0
                                    1                      404.0                                          244.0
                                    3                      376.0                                          386.0
                                    4                      390.0                                          396.0
                                    5                      386.0                                          388.0
...                                                                                                         ...
VP_032      tsst      Talk          39                     310.0                                          324.0
                                    40                     322.0                                          330.0
                                    41                     340.0                                          348.0
                                    42                     311.0                                          366.0
                                    43                     307.0                                          356.0

                                                                                     debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                            452.0
                                    1                      404.0                                            388.0
                                    3                      376.0                                            366.0
                                    4                      390.0                                            376.0
                                    5                      386.0                                            418.0
...                                                                                                           ...
VP_032      tsst      Talk          39                     310.0                                            300.0
                                    40                     322.0                                            311.0
                                    41                     340.0                                            330.0
                                    42                     311.0                                            347.0
                                    43                     307.0                                            285.0

                                                                                     drost2022  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                         400.0
                                    1                      404.0                         420.0
                                    3                      376.0                         386.0
                                    4                      390.0                         396.0
                                    5                      386.0                         392.0
...                                                                                        ...
VP_032      tsst      Talk          39                     310.0                         318.0
                                    40                     322.0                         322.0
                                    41                     340.0                         343.0
                                    42                     311.0                         354.0
                                    43                     307.0                         332.0

                                                                                     forouzanfar2018  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                               550.0
                                    1                      404.0                               402.0
                                    3                      376.0                               388.0
                                    4                      390.0                               398.0
                                    5                      386.0                               390.0
...                                                                                              ...
VP_032      tsst      Talk          39                     310.0                               306.0
                                    40                     322.0                               311.0
                                    41                     340.0                               309.0
                                    42                     311.0                               305.0
                                    43                     307.0                               302.0

                                                                                     lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                            412.0
                                    1                      404.0                                            404.0
                                    3                      376.0                                            366.0
                                    4                      390.0                                            372.0
                                    5                      386.0                                            378.0
...                                                                                                           ...
VP_032      tsst      Talk          39                     310.0                                            305.0
                                    40                     322.0                                            321.0
                                    41                     340.0                                            332.0
                                    42                     311.0                                            351.0
                                    43                     307.0                                            341.0

                                                                                     lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                               384.0
                                    1                      404.0                                               384.0
                                    3                      376.0                                               348.0
                                    4                      390.0                                               348.0
                                    5                      386.0                                               354.0
...                                                                                                              ...
VP_032      tsst      Talk          39                     310.0                                               294.0
                                    40                     322.0                                               303.0
                                    41                     340.0                                               322.0
                                    42                     311.0                                               337.0
                                    43                     307.0                                               329.0

                                                                                     miljkovic2022  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                             442.0
                                    1                      404.0                             288.0
                                    3                      376.0                             386.0
                                    4                      390.0                             398.0
                                    5                      386.0                             392.0
...                                                                                            ...
VP_032      tsst      Talk          39                     310.0                             308.0
                                    40                     322.0                             329.0
                                    41                     340.0                             292.0
                                    42                     311.0                             312.0
                                    43                     307.0                             334.0

                                                                                     ...  \
participant condition phase         heartbeat_id_reference b_point_sample_reference  ...
GDN0005     Dummy     HoldingBreath 0                      388.0                     ...
                                    1                      404.0                     ...
                                    3                      376.0                     ...
                                    4                      390.0                     ...
                                    5                      386.0                     ...
...                                                                                  ...
VP_032      tsst      Talk          39                     310.0                     ...
                                    40                     322.0                     ...
                                    41                     340.0                     ...
                                    42                     311.0                     ...
                                    43                     307.0                     ...

                                                                                     SS_KBest_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                                  412.398584
                                    1                      404.0                                                  403.408903
                                    3                      376.0                                                  376.768489
                                    4                      390.0                                                  388.625256
                                    5                      386.0                                                  385.761830
...                                                                                                                      ...
VP_032      tsst      Talk          39                     310.0                                                  309.424969
                                    40                     322.0                                                  312.280534
                                    41                     340.0                                                  331.079043
                                    42                     311.0                                                  342.187956
                                    43                     307.0                                                  307.324979

                                                                                     SS_KBest_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                                  421.288455
                                    1                      404.0                                                  401.485786
                                    3                      376.0                                                  376.403625
                                    4                      390.0                                                  388.643213
                                    5                      386.0                                                  386.743597
...                                                                                                                      ...
VP_032      tsst      Talk          39                     310.0                                                  319.918637
                                    40                     322.0                                                  317.460122
                                    41                     340.0                                                  329.227094
                                    42                     311.0                                                  339.654610
                                    43                     307.0                                                  314.443751

                                                                                     MinMax_SFM_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                                         392.0
                                    1                      404.0                                                         406.0
                                    3                      376.0                                                         376.0
                                    4                      390.0                                                         388.0
                                    5                      386.0                                                         384.0
...                                                                                                                        ...
VP_032      tsst      Talk          39                     310.0                                                         311.0
                                    40                     322.0                                                         321.0
                                    41                     340.0                                                         334.0
                                    42                     311.0                                                         351.5
                                    43                     307.0                                                         307.5

                                                                                     MinMax_SFM_RFR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference

In [6]:
merged_ml_results_b_point = merged_ml_results_b_point.drop(columns=["level_0"])
merged_ml_results_b_point

                                                                                     arbol2017-isoelectric-crossings  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                               438.0
                                    1                      404.0                                               340.0
                                    3                      376.0                                               382.0
                                    4                      390.0                                               394.0
                                    5                      386.0                                               398.0
...                                                                                                              ...
VP_032      tsst      Talk          39                     310.0                                               335.0
                                    40                     322.0                                               331.0
                                    41                     340.0                                               317.0
                                    42                     311.0                                               365.0
                                    43                     307.0                                               342.0

                                                                                     arbol2017-second-derivative  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                           398.0
                                    1                      404.0                                           350.0
                                    3                      376.0                                           296.0
                                    4                      390.0                                           344.0
                                    5                      386.0                                           312.0
...                                                                                                          ...
VP_032      tsst      Talk          39                     310.0                                           276.0
                                    40                     322.0                                           298.0
                                    41                     340.0                                           300.0
                                    42                     311.0                                           324.0
                                    43                     307.0                                           313.0

                                                                                     arbol2017-third-derivative  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                          394.0
                                    1                      404.0                                          244.0
                                    3                      376.0                                          386.0
                                    4                      390.0                                          396.0
                                    5                      386.0                                          388.0
...                                                                                                         ...
VP_032      tsst      Talk          39                     310.0                                          324.0
                                    40                     322.0                                          330.0
                                    41                     340.0                                          348.0
                                    42                     311.0                                          366.0
                                    43                     307.0                                          356.0

                                                                                     debski1993-second-derivative  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                            452.0
                                    1                      404.0                                            388.0
                                    3                      376.0                                            366.0
                                    4                      390.0                                            376.0
                                    5                      386.0                                            418.0
...                                                                                                           ...
VP_032      tsst      Talk          39                     310.0                                            300.0
                                    40                     322.0                                            311.0
                                    41                     340.0                                            330.0
                                    42                     311.0                                            347.0
                                    43                     307.0                                            285.0

                                                                                     drost2022  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                         400.0
                                    1                      404.0                         420.0
                                    3                      376.0                         386.0
                                    4                      390.0                         396.0
                                    5                      386.0                         392.0
...                                                                                        ...
VP_032      tsst      Talk          39                     310.0                         318.0
                                    40                     322.0                         322.0
                                    41                     340.0                         343.0
                                    42                     311.0                         354.0
                                    43                     307.0                         332.0

                                                                                     forouzanfar2018  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                               550.0
                                    1                      404.0                               402.0
                                    3                      376.0                               388.0
                                    4                      390.0                               398.0
                                    5                      386.0                               390.0
...                                                                                              ...
VP_032      tsst      Talk          39                     310.0                               306.0
                                    40                     322.0                               311.0
                                    41                     340.0                               309.0
                                    42                     311.0                               305.0
                                    43                     307.0                               302.0

                                                                                     lozano2007-linear-regression  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                            412.0
                                    1                      404.0                                            404.0
                                    3                      376.0                                            366.0
                                    4                      390.0                                            372.0
                                    5                      386.0                                            378.0
...                                                                                                           ...
VP_032      tsst      Talk          39                     310.0                                            305.0
                                    40                     322.0                                            321.0
                                    41                     340.0                                            332.0
                                    42                     311.0                                            351.0
                                    43                     307.0                                            341.0

                                                                                     lozano2007-quadratic-regression  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                               384.0
                                    1                      404.0                                               384.0
                                    3                      376.0                                               348.0
                                    4                      390.0                                               348.0
                                    5                      386.0                                               354.0
...                                                                                                              ...
VP_032      tsst      Talk          39                     310.0                                               294.0
                                    40                     322.0                                               303.0
                                    41                     340.0                                               322.0
                                    42                     311.0                                               337.0
                                    43                     307.0                                               329.0

                                                                                     miljkovic2022  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                             442.0
                                    1                      404.0                             288.0
                                    3                      376.0                             386.0
                                    4                      390.0                             398.0
                                    5                      386.0                             392.0
...                                                                                            ...
VP_032      tsst      Talk          39                     310.0                             308.0
                                    40                     322.0                             329.0
                                    41                     340.0                             292.0
                                    42                     311.0                             312.0
                                    43                     307.0                             334.0

                                                                                     pale2021  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                        388.0
                                    1                      404.0                        246.0
                                    3                      376.0                        374.0
                                    4                      390.0                        388.0
                                    5                      386.0                        384.0
...                                                                                       ...
VP_032      tsst      Talk          39                     310.0                        306.0
                                    40                     322.0                         85.0
                                    41                     340.0                         14.0
                                    42                     311.0                        261.0
                                    43                     307.0                        302.0

                                                                                     ...  \
participant condition phase         heartbeat_id_reference b_point_sample_reference  ...
GDN0005     Dummy     HoldingBreath 0                      388.0                     ...
                                    1                      404.0                     ...
                                    3                      376.0                     ...
                                    4                      390.0                     ...
                                    5                      386.0                     ...
...                                                                                  ...
VP_032      tsst      Talk          39                     310.0                     ...
                                    40                     322.0                     ...
                                    41                     340.0                     ...
                                    42                     311.0                     ...
                                    43                     307.0                     ...

                                                                                     SS_KBest_SVR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                                  412.398584
                                    1                      404.0                                                  403.408903
                                    3                      376.0                                                  376.768489
                                    4                      390.0                                                  388.625256
                                    5                      386.0                                                  385.761830
...                                                                                                                      ...
VP_032      tsst      Talk          39                     310.0                                                  309.424969
                                    40                     322.0                                                  312.280534
                                    41                     340.0                                                  331.079043
                                    42                     311.0                                                  342.187956
                                    43                     307.0                                                  307.324979

                                                                                     SS_KBest_KNR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                                  421.288455
                                    1                      404.0                                                  401.485786
                                    3                      376.0                                                  376.403625
                                    4                      390.0                                                  388.643213
                                    5                      386.0                                                  386.743597
...                                                                                                                      ...
VP_032      tsst      Talk          39                     310.0                                                  319.918637
                                    40                     322.0                                                  317.460122
                                    41                     340.0                                                  329.227094
                                    42                     311.0                                                  339.654610
                                    43                     307.0                                                  314.443751

                                                                                     MinMax_SFM_DTR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference
GDN0005     Dummy     HoldingBreath 0                      388.0                                                         392.0
                                    1                      404.0                                                         406.0
                                    3                      376.0                                                         376.0
                                    4                      390.0                                                         388.0
                                    5                      386.0                                                         384.0
...                                                                                                                        ...
VP_032      tsst      Talk          39                     310.0                                                         311.0
                                    40                     322.0                                                         321.0
                                    41                     340.0                                                         334.0
                                    42                     311.0                                                         351.5
                                    43                     307.0                                                         307.5

                                                                                     MinMax_SFM_RFR_RR-Interval-Median-Imputed  \
participant condition phase         heartbeat_id_reference b_point_sample_reference

### Save merged dataframe

In [ ]:
# merged_ml_results_b_point.to_csv(data_path.joinpath('merged_ml_results_b_point_paper_rr_only.csv'))